baseurl: "https://chuncane.com/"
DefaultContentLanguage: "es"
languageCode: "es-ar"
title: "Inicio"
params:
  description: Lo que nos hace Ãºnicos 
  images:
  - '/img/quilt2.png'
  title: Chuncane
googleAnalytics: UA-141188337-1
